# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180328_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=20, verbose_name='访问地址'),
        ),
    ]
