# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180328_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, verbose_name='视频名称'),
        ),
    ]
